replicaCount: 1

frontend:
  repository: skpdoc15/frontend
  tag: 4a1ea1e69c843940a955ec8f78c60785d12e7b2b

backend:
  repository: skpdoc15/backend
  tag: 4a1ea1e69c843940a955ec8f78c60785d12e7b2b


postgres:
  user: admin
  password: password
  database: tasksdb

redis:
  image: redis:7

service:
  type: NodePort
  port: 80
  nodeport: 30080

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
