replicaCount: 1

frontend:
  repository: skpdoc15/frontend
  tag: 780e5729b63b808bf9e80fa45082e71d40e7882d

backend:
  repository: skpdoc15/backend
  tag: 780e5729b63b808bf9e80fa45082e71d40e7882d


postgres:
  user: admin
  password: password
  database: tasksdb

redis:
  image: redis:7

service:
  type: NodePort
  port: 80
  nodeport: 30080

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
