
frontend:
  replicaCount: 2
  repository: skpdoc15/frontend
  tag: 1b9e6939cd5d448e56bce1b61c89f5c6767183bd

backend:
  replicaCount: 1
  repository: skpdoc15/backend
  tag: 1b9e6939cd5d448e56bce1b61c89f5c6767183bd


postgres:
  replicaCount: 1
  user: admin
  password: password
  database: tasksdb

redis:
  replicaCount: 1
  image: redis:7

service:
  type: NodePort
  port: 80
  nodeport: 30080

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
